[package]
name = "rust-gw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
async-std = { version = "1.10.0", features = ["attributes"] }
actix-web = "3.3.3"
reqwest = "0.11.9"